language: java

addons:
  sonarcloud:
    organization: "sajjaadalipour"

services:
  - redis-server

matrix:
  include:
    - jdk: openjdk8
      os:  linux
      env: JAVA_VERSION=1.8
    - jdk: openjdk9
      os:  linux
      env: JAVA_VERSION=9
    - jdk: openjdk10
      os:  linux
      env: JAVA_VERSION=10
    - jdk: openjdk11
      os: linux
      env: JAVA_VERSION=11

install: true

script:
  - chmod +x mvnw
  - ./mvnw clean verify sonar:sonar -Dsonar.projectKey=sajjaadalipour_ratelimit-spring-boot-starter
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.m2/repository